### ISSUE TITLE
data freshness labels not accurate re missing info (is this becuase of the state of deployment?)

### ISSUE THREAD

**Issue by jbeard4** [streetlives/streetlives-web#39]
Date Reported: 4/27/2018

Reporter: AB

Steps to reproduce: 1. Edit POI. 2. Tap field with red missing info data label (e.g. on address). 3. Address is visible (i.e. not missing) 4. Tap YES, 5. Return to List, 6. data label still showing as missing info

Dev assigned: Jake

Dev notes: Basic functionality

**Comment by adambard1** [comment]
When is this getting pushed to prod, pls – also does it cover the issue for dropping a new pin and seeing only green labels when all that has been created is the name of the org? i.e. there'll be a yellow label for missing data on new locations too.

**Comment by jbeard4** [comment]
I will wrap this up this week.
